export const recalculateParamsWoman = [
    {
        imgUrl: "static/img/dataImg/women/bg-16.png",
        secondImgUrl: "static/img/dataImg/women/002-body1.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-20.png",
        secondImgUrl: "static/img/dataImg/women/002-body2-1.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 50,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-55.png",
        secondImgUrl: "static/img/dataImg/women/001-waist1.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-5.png",
        secondImgUrl: "static/img/dataImg/women/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 18,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-28.png",
        secondImgUrl: "static/img/dataImg/women/firm.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 200,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-32.png",
        secondImgUrl: "static/img/dataImg/women/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-36.png",
        secondImgUrl: "static/img/dataImg/women/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-40.png",
        secondImgUrl: "static/img/dataImg/women/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 12,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-1.png",
        secondImgUrl: "static/img/dataImg/women/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 10,
        sizeMax: 18,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-52.png",
        secondImgUrl: "static/img/dataImg/women/002-body4.png",
        title: "Обхват талии на уровне пупка",
        text: "Оберните ленту горизонтально на уровне пупка",
        inputName: "waistAtNavelLevel",
        sizeMin: 55,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-48.png",
        secondImgUrl: "static/img/dataImg/women/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 33,
        sizeMax: 48,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-63.png",
        secondImgUrl: "static/img/dataImg/women/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-59.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-71.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "WideFootGirth",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-67.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 50,
        sizeMax: 100,
    },
];
export const recalculateParamsMan = [
    {
        imgUrl: "static/img/dataImg/men/bg-16.png",
        secondImgUrl: "static/img/dataImg/men/003-man.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-20.png",
        secondImgUrl: "static/img/dataImg/men/002-man.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 50,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-55.png",
        secondImgUrl: "static/img/dataImg/men/005-man.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-5.png",
        secondImgUrl: "static/img/dataImg/men/004-man.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 18,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-28.png",
        secondImgUrl: "static/img/dataImg/men/006-man.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 200,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-32.png",
        secondImgUrl: "static/img/dataImg/men/007-man.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-36.png",
        secondImgUrl: "static/img/dataImg/men/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-40.png",
        secondImgUrl: "static/img/dataImg/men/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 12,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-1.png",
        secondImgUrl: "static/img/dataImg/men/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 10,
        sizeMax: 18,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-52.png",
        secondImgUrl: "static/img/dataImg/men/002-man.png",
        title: "Обхват талии на уровне пупка",
        text: "Оберните ленту горизонтально на уровне пупка",
        inputName: "waistAtNavelLevel",
        sizeMin: 55,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-48.png",
        secondImgUrl: "static/img/dataImg/men/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 33,
        sizeMax: 48,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-63.png",
        secondImgUrl: "static/img/dataImg/men/legs-frontal.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-59.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-71.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "WideFootGirth",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-67.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 50,
        sizeMax: 100,
    },
];
export const recalculateParamsGirl = [
    {
        imgUrl: "static/img/dataImg/girl/bg-16.png",
        secondImgUrl: "static/img/dataImg/girl/002-body1.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-20.png",
        secondImgUrl: "static/img/dataImg/girl/002-body2.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 50,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-55.png",
        secondImgUrl: "static/img/dataImg/girl/001-waist1.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-5.png",
        secondImgUrl: "static/img/dataImg/girl/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 18,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-28.png",
        secondImgUrl: "static/img/dataImg/girl/firm.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 200,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-32.png",
        secondImgUrl: "static/img/dataImg/girl/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-36.png",
        secondImgUrl: "static/img/dataImg/girl/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-40.png",
        secondImgUrl: "static/img/dataImg/girl/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 12,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-44.png",
        secondImgUrl: "static/img/dataImg/girl/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 10,
        sizeMax: 18,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-52.png",
        secondImgUrl: "static/img/dataImg/girl/002-body4.png",
        title: "Обхват талии на уровне пупка",
        text: "Оберните ленту горизонтально на уровне пупка",
        inputName: "waistAtNavelLevel",
        sizeMin: 55,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-48.png",
        secondImgUrl: "static/img/dataImg/girl/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 33,
        sizeMax: 48,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-63.png",
        secondImgUrl: "static/img/dataImg/girl/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-59.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-71.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "WideFootGirth",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-67.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 50,
        sizeMax: 100,
    },
];
export const recalculateParamsBoy = [
    {
        imgUrl: "static/img/dataImg/boy/bg-16.png",
        secondImgUrl: "static/img/dataImg/boy/003-man.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-20.png",
        secondImgUrl: "static/img/dataImg/boy/002-man.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 50,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/005-man.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 18,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-28.png",
        secondImgUrl: "static/img/dataImg/boy/006-man.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 200,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-36.png",
        secondImgUrl: "static/img/dataImg/boy/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-40.png",
        secondImgUrl: "static/img/dataImg/boy/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 12,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-44.png",
        secondImgUrl: "static/img/dataImg/boy/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 10,
        sizeMax: 18,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-20.png",
        secondImgUrl: "static/img/dataImg/boy/002-man.png",
        title: "Обхват талии на уровне пупка",
        text: "Оберните ленту горизонтально на уровне пупка",
        inputName: "waistAtNavelLevel",
        sizeMin: 55,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-48.png",
        secondImgUrl: "static/img/dataImg/boy/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 33,
        sizeMax: 48,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-63.png",
        secondImgUrl: "static/img/dataImg/boy/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-59.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-71.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "WideFootGirth",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-67.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 50,
        sizeMax: 100,
    },
];
export const recalculateParamsDog = [
    {
        imgUrl: "static/img/dataImg/dog/bg-1.png",
        secondImgUrl: "static/img/dataImg/dog/dog2.png",
        title: "Обхват шеи",
        text: "",
        inputName: "neckGirth",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-2.png",
        secondImgUrl: "static/img/dataImg/dog/dog1.png",
        title: "Длина передних лап",
        text: "",
        inputName: "frontPawsLength",
        sizeMin: 70,
        sizeMax: 140,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-3.png",
        secondImgUrl: "static/img/dataImg/dog/dog3.png",
        title: "Обхват груди",
        text: "",
        inputName: "chestGirth",
        sizeMin: 18,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-4.png",
        secondImgUrl: "static/img/dataImg/dog/dog5.png",
        title: "Длина спины",
        text: "",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 200,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-5.png",
        secondImgUrl: "static/img/dataImg/dog/dog6.png",
        title: "Объем талии",
        text: "",
        inputName: "waist",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-6.png",
        secondImgUrl: "static/img/dataImg/dog/dog4.png",
        title: "Длина задних лап",
        text: "",
        inputName: "hindFeetLength",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-7.png",
        secondImgUrl: "static/img/dataImg/dog/paw2.png",
        title: "Длина ноги",
        text: "",
        inputName: "legLength",
        sizeMin: 12,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-8.png",
        secondImgUrl: "static/img/dataImg/dog/paw1.png",
        title: "ширина ноги",
        text: "",
        inputName: "legWidth",
        sizeMin: 10,
        sizeMax: 18,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-9.png",
        secondImgUrl: "static/img/dataImg/dog/paw3.png",
        title: "Обхват ноги",
        text: "",
        inputName: "legCircumference",
        sizeMin: 55,
        sizeMax: 140,
    },
];