export const recalculateParamsWoman = [
    {
        imgUrl: "static/img/dataImg/women/bg-16.png",
        secondImgUrl: "static/img/dataImg/women/002-body1.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 60,
        sizeMax: 160,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-20.png",
        secondImgUrl: "static/img/dataImg/women/002-body2-1.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 40,
        sizeMax: 150,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-55.png",
        secondImgUrl: "static/img/dataImg/women/001-waist1.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 70,
        sizeMax: 170,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-5.png",
        secondImgUrl: "static/img/dataImg/women/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 15,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-28.png",
        secondImgUrl: "static/img/dataImg/women/firm.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 140,
        sizeMax: 210,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-32.png",
        secondImgUrl: "static/img/dataImg/women/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 40,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-36.png",
        secondImgUrl: "static/img/dataImg/women/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 40,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-40.png",
        secondImgUrl: "static/img/dataImg/women/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 12,
        sizeMax: 29,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-1.png",
        secondImgUrl: "static/img/dataImg/women/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 9,
        sizeMax: 19,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-52.png",
        secondImgUrl: "static/img/dataImg/women/002-body4.png",
        title: "Длинна руки",
        text: "Измеряйте от косточки плеча до косточки кисти",
        inputName: "armLength",
        sizeMin: 55,
        sizeMax: 70,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-48.png",
        secondImgUrl: "static/img/dataImg/women/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 33,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-63.png",
        secondImgUrl: "static/img/dataImg/women/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 50,
        sizeMax: 100,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-59.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 13,
        sizeMax: 35,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-71.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "wideFootGirth",
        sizeMin: 8,
        sizeMax: 32,
    },
    {
        imgUrl: "static/img/dataImg/women/bg-67.png",
        secondImgUrl: "static/img/dataImg/women/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 8,
        sizeMax: 32,
    },
];
export const recalculateParamsMan = [
    {
        imgUrl: "static/img/dataImg/men/bg-16.png",
        secondImgUrl: "static/img/dataImg/men/003-man.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 75,
        sizeMax: 169,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-20.png",
        secondImgUrl: "static/img/dataImg/men/002-man.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 60,
        sizeMax: 160,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-55.png",
        secondImgUrl: "static/img/dataImg/men/005-man.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 80,
        sizeMax: 160,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-5.png",
        secondImgUrl: "static/img/dataImg/men/004-man.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 20,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-28.png",
        secondImgUrl: "static/img/dataImg/men/006-man.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 150,
        sizeMax: 220,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-32.png",
        secondImgUrl: "static/img/dataImg/men/007-man.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 45,
        sizeMax: 90,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-36.png",
        secondImgUrl: "static/img/dataImg/men/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 50,
        sizeMax: 70,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-40.png",
        secondImgUrl: "static/img/dataImg/men/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 17,
        sizeMax: 30,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-1.png",
        secondImgUrl: "static/img/dataImg/men/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 11,
        sizeMax: 17,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-52.png",
        secondImgUrl: "static/img/dataImg/men/002-man.png",
        title: "Длинна руки",
        text: "Измеряйте от косточки плеча до косточки кисти",
        inputName: "armLength",
        sizeMin: 40,
        sizeMax: 75,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-48.png",
        secondImgUrl: "static/img/dataImg/men/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 35,
        sizeMax: 70,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-63.png",
        secondImgUrl: "static/img/dataImg/men/legs-frontal.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 60,
        sizeMax: 110,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-59.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 15,
        sizeMax: 40,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-71.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "wideFootGirth",
        sizeMin: 10,
        sizeMax: 35,
    },
    {
        imgUrl: "static/img/dataImg/men/bg-67.png",
        secondImgUrl: "static/img/dataImg/men/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 10,
        sizeMax: 35,
    },
];
export const recalculateParamsGirl = [
    {
        imgUrl: "static/img/dataImg/girl/bg-16.png",
        secondImgUrl: "static/img/dataImg/girl/002-body1.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 32,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-20.png",
        secondImgUrl: "static/img/dataImg/girl/002-body2.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 30,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-55.png",
        secondImgUrl: "static/img/dataImg/girl/001-waist1.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 40,
        sizeMax: 160,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-5.png",
        secondImgUrl: "static/img/dataImg/girl/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 5,
        sizeMax: 40,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-28.png",
        secondImgUrl: "static/img/dataImg/girl/firm.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 40,
        sizeMax: 210,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-32.png",
        secondImgUrl: "static/img/dataImg/girl/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 10,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-36.png",
        secondImgUrl: "static/img/dataImg/girl/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 30,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-40.png",
        secondImgUrl: "static/img/dataImg/girl/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 11,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-44.png",
        secondImgUrl: "static/img/dataImg/girl/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 3,
        sizeMax: 16,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-52.png",
        secondImgUrl: "static/img/dataImg/girl/002-body4.png",
        title: "Длинна руки",
        text: "Измеряйте от косточки плеча до косточки кисти",
        inputName: "armLength",
        sizeMin: 20,
        sizeMax: 60,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-48.png",
        secondImgUrl: "static/img/dataImg/girl/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 15,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-63.png",
        secondImgUrl: "static/img/dataImg/girl/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 30,
        sizeMax: 90,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-59.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 5,
        sizeMax: 30,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-71.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "wideFootGirth",
        sizeMin: 4,
        sizeMax: 25,
    },
    {
        imgUrl: "static/img/dataImg/girl/bg-67.png",
        secondImgUrl: "static/img/dataImg/girl/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 4,
        sizeMax: 25,
    },
];
export const recalculateParamsBoy = [
    {
        imgUrl: "static/img/dataImg/boy/bg-16.png",
        secondImgUrl: "static/img/dataImg/boy/003-man.png",
        title: "Грудь",
        text: "Обхват груди в наиболее выступающих точках. Лента проходит по нижней части лопаток",
        inputName: "chest",
        sizeMin: 32,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-20.png",
        secondImgUrl: "static/img/dataImg/boy/002-man.png",
        title: "Талия",
        text: "Обхват талии в самом узком месте. Лента паралельно полу",
        inputName: "waist",
        sizeMin: 30,
        sizeMax: 130,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/005-man.png",
        title: "Бедра",
        text: "Обхват бедра в наиболее выступающих точках. Ноги вместе",
        inputName: "hips",
        sizeMin: 40,
        sizeMax: 160,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/002-body3.png",
        title: "Обхват руки",
        text: "Обхват руки в самом широком месте предплечья",
        inputName: "armGirth",
        sizeMin: 5,
        sizeMax: 40,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-28.png",
        secondImgUrl: "static/img/dataImg/boy/006-man.png",
        title: "Рост",
        text: "Укажите свой рост",
        inputName: "growth",
        sizeMin: 40,
        sizeMax: 210,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-32.png",
        secondImgUrl: "static/img/dataImg/boy/001-waist2.png",
        title: "Обхват бедра",
        text: "Измеряйте в самом широком месте бедра, под ягодичной складкой",
        inputName: "thighGirth",
        sizeMin: 10,
        sizeMax: 80,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-36.png",
        secondImgUrl: "static/img/dataImg/boy/woman-hair1.png",
        title: "Обхват головы",
        text: "Оберните ленту вокруг головы. Лента должна проходить по самым выступающим частям лба и затылка над ушами",
        inputName: "headCircumference",
        sizeMin: 30,
        sizeMax: 65,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-40.png",
        secondImgUrl: "static/img/dataImg/boy/stop1.png",
        title: "Обхват ладони",
        text: "Измеряйте в самом широком месте ладони (без большого пальца)",
        inputName: "palmGirth",
        sizeMin: 11,
        sizeMax: 28,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-44.png",
        secondImgUrl: "static/img/dataImg/boy/stop2.png",
        title: "Длина пальцев",
        text: "Измеряйте от основания большого пальца до кончика среднего пальца",
        inputName: "fingerLength",
        sizeMin: 3,
        sizeMax: 16,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-20.png",
        secondImgUrl: "static/img/dataImg/boy/002-man.png",
        title: "Длинна руки",
        text: "Измеряйте от косточки плеча до косточки кисти",
        inputName: "armLength",
        sizeMin: 20,
        sizeMax: 60,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-48.png",
        secondImgUrl: "static/img/dataImg/boy/shoulder.png",
        title: "Ширина плеч",
        text: "Нащупайте крайнюю точку плечевой косточки. Набросьте ленту на плечи и измерьте расстояние между плечевыми точками",
        inputName: "shoulder",
        sizeMin: 15,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-63.png",
        secondImgUrl: "static/img/dataImg/boy/woman-stretching-left-leg.png",
        title: "Длина ноги по внутренней части",
        text: "Оберните ленту ***",
        inputName: "insideLegLength",
        sizeMin: 30,
        sizeMax: 90,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-59.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_3.png",
        title: "Длина стопы",
        text: "Оберните ленту ***",
        inputName: "footLength",
        sizeMin: 5,
        sizeMax: 30,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-71.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_1.png",
        title: "Обхват стопы в щироком месте",
        text: "Оберните ленту ***",
        inputName: "wideFootGirth",
        sizeMin: 4,
        sizeMax: 25,
    },
    {
        imgUrl: "static/img/dataImg/boy/bg-67.png",
        secondImgUrl: "static/img/dataImg/boy/002-human-foot2_2.png",
        title: "Обхват объема (талии стопы)",
        text: "Оберните ленту ***",
        inputName: "footCircumference",
        sizeMin: 4,
        sizeMax: 25,
    },
];
export const recalculateParamsDog = [
    {
        imgUrl: "static/img/dataImg/dog/bg-1.png",
        secondImgUrl: "static/img/dataImg/dog/dog2.png",
        title: "Обхват шеи",
        text: "",
        inputName: "neckGirth",
        sizeMin: 10,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-2.png",
        secondImgUrl: "static/img/dataImg/dog/dog1.png",
        title: "Длина передних лап",
        text: "",
        inputName: "frontPawsLength",
        sizeMin: 5,
        sizeMax: 40,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-3.png",
        secondImgUrl: "static/img/dataImg/dog/dog3.png",
        title: "Обхват груди",
        text: "",
        inputName: "chestGirth",
        sizeMin: 20,
        sizeMax: 70,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-4.png",
        secondImgUrl: "static/img/dataImg/dog/dog5.png",
        title: "Длина спины",
        text: "",
        inputName: "growthDog",
        sizeMin: 10,
        sizeMax: 50,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-5.png",
        secondImgUrl: "static/img/dataImg/dog/dog6.png",
        title: "Объем талии",
        text: "",
        inputName: "waistDog",
        sizeMin: 10,
        sizeMax: 60,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-6.png",
        secondImgUrl: "static/img/dataImg/dog/dog4.png",
        title: "Длина задних лап",
        text: "",
        inputName: "hindFeetLength",
        sizeMin: 5,
        sizeMax: 45,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-7.png",
        secondImgUrl: "static/img/dataImg/dog/paw2.png",
        title: "Длина лапы",
        text: "",
        inputName: "legLength",
        sizeMin: 4,
        sizeMax: 45,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-8.png",
        secondImgUrl: "static/img/dataImg/dog/paw1.png",
        title: "ширина лапы",
        text: "",
        inputName: "legWidth",
        sizeMin: 2,
        sizeMax: 20,
    },
    {
        imgUrl: "static/img/dataImg/dog/bg-9.png",
        secondImgUrl: "static/img/dataImg/dog/paw3.png",
        title: "Обхват лапы",
        text: "",
        inputName: "legCircumference",
        sizeMin: 2,
        sizeMax: 20,
    },
];


// 0: chest - Грудь
// 1: waist - Талия
// 2: hips - Бедра
// 3: armGirth - Обхват руки
// 4: growth - Рост
// 5: thighGirth - Обхват бедра
// 6: headCircumference - Обхват головы
// 7: palmGirth - Обхват ладони
// 8: fingerLength - Длина пальцев
// 9: armLength - Длинна руки
// 10: shoulder - Ширина плеч
// 11: insideLegLength - Длина ноги по внутренней части
// 12: footLength - Длина стопы
// 13: wideFootGirth - Обхват стопы в щироком месте
// 14: footCircumference - Обхват объема (талии стопы)

export const sizeListTshirts = [
    "chest",
    "waist",
    "hips",
    "armGirth",
    "growth",
    "shoulder",
];
export const sizeListShirts = [
    "chest",
    "waist",
    "hips",
    "armGirth",
    "growth",
    "armLength",
    "shoulder",
];
export const sizeListPants = [
    "waist",
    "hips",
    "growth",
    "thighGirth",
    "insideLegLength",
];
export const sizeListUnderwear = [
    "chest",
    "waist",
    "hips",
    "growth",
    "thighGirth",
    "insideLegLength",
];
export const sizeListOuterwear = [
    "chest",
    "waist",
    "hips",
    "armGirth",
    "growth",
    "armLength",
    "shoulder",
];
export const sizeListHome = [
    "chest",
    "waist",
    "hips",
    "growth",
    "armLength",
    "shoulder",
    "insideLegLength",
];

// DOG
// 0: neckGirth - Обхват шеи
// 1: frontPawsLength - Длина передних лап
// 2: chestGirth - Обхват груди
// 3: growthDog - Длина спины
// 4: waistDog - Объем талии
// 5: hindFeetLength - Длина задних лап
// 6: legLength - Длина лапы
// 7: legWidth - ширина лапы
// 8: legCircumference - Обхват лапы

export const dogSizeListPants = [
    "growthDog",
    "waistDog",
    "hindFeetLength",
];
export const dogSizeListShirts = [
    "neckGirth",
    "frontPawsLength",
    "chestGirth",
    "growthDog",
];
export const dogSizeListOuterwear = [
    "neckGirth",
    "frontPawsLength",
    "chestGirth",
    "growthDog",
    "waistDog",
    "hindFeetLength",
    "legLength",
    "legWidth",
    "legCircumference",
];
export const dogSizeListShoes = [
    "legLength",
    "legWidth",
    "legCircumference",
];
